apiVersion: v1
kind: Service
metadata:
  name: janik-kustomize-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: janik-instance
    app.kubernetes.io/name: janik-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: None